"""Base types for the vocabulary system; pack ``.py`` files are generated by ``scripts/generate_vocabulary.py`` — do not hand-edit them."""

from __future__ import annotations

import functools
from collections.abc import Iterator
from dataclasses import dataclass, field

_KIND_NAMES = {
    0: "Marker",
    1: "Bool",
    2: "Number",
    3: "Str",
    4: "Ref",
    5: "Uri",
    6: "Date",
    7: "Time",
    8: "DateTime",
    9: "Coord",
    10: "XStr",
}


@dataclass(frozen=True, slots=True)
class TagDef:
    """A single tag definition, mirroring the legacy ``HaystackTagDef`` Django model; ``kind`` is an int code for wire compatibility."""

    name: str
    display_name: str
    kind: int  # Use kind_name() for the human-readable label
    namespace: str = "phIoT"
    doc: str = ""
    supertype: str | None = None
    unit_quantity: str | None = None

    def kind_name(self) -> str:
        return _KIND_NAMES.get(self.kind, "Unknown")

    @property
    def is_marker(self) -> bool:
        return self.kind == 0


@dataclass(frozen=True)
class Vocabulary:
    """A named collection of :class:`TagDef` records."""

    name: str
    version: str
    tags: tuple[TagDef, ...] = field(default_factory=tuple)

    def __iter__(self) -> Iterator[TagDef]:
        return iter(self.tags)

    def __len__(self) -> int:
        return len(self.tags)

    def __contains__(self, name: object) -> bool:
        if not isinstance(name, str):
            return False
        return self.get(name) is not None

    def get(self, name: str) -> TagDef | None:
        for tag in self.tags:
            if tag.name == name:
                return tag
        return None

    @functools.cached_property
    def _names_cache(self) -> frozenset[str]:
        return frozenset(t.name for t in self.tags)

    def names(self) -> frozenset[str]:
        return self._names_cache
